services:
  app:
    build: .
    image: epoch-gold
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/config/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USERNAME} -d $${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: