services:
  app:
    build: .
    image: epoch-gold
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
